# Flask Build
FROM python:3.10
RUN apt -y update
RUN apt install -y python3-pip build-essential nodejs npm
COPY . .
RUN npm run build
RUN pip3 install -r requirements.txt
ENTRYPOINT [ "python3" ]
CMD ["main.py"]